// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmoeLJQwHMUJgtd-UI9Q9t8vsxebS6fGw',
    appId: '1:504400761702:web:6ccc6eca37806a4ea92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    authDomain: 'smartlink-pro.firebaseapp.com',
    databaseURL: 'https://smartlink-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartlink-pro.appspot.com',
    measurementId: 'G-E24RCMVDJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIO_HwRMwRt_j_TYu_s2NjQ0bufHyv6o',
    appId: '1:504400761702:android:8010201d2dd1529aa92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    databaseURL: 'https://smartlink-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartlink-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_foRrtanDZ_9IeOiAuMdgdhUD9HxSqE',
    appId: '1:504400761702:ios:46d889cef781c621a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    databaseURL: 'https://smartlink-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartlink-pro.appspot.com',
    androidClientId: '504400761702-2h2ffa1qo66lvn6pvo8le3c63kap7291.apps.googleusercontent.com',
    iosClientId: '504400761702-bd68e16snrrbduu1duqev2ir08bhmb1g.apps.googleusercontent.com',
    iosBundleId: 'com.smartlink.smartlinkAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_foRrtanDZ_9IeOiAuMdgdhUD9HxSqE',
    appId: '1:504400761702:ios:46d889cef781c621a92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    databaseURL: 'https://smartlink-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartlink-pro.appspot.com',
    androidClientId: '504400761702-2h2ffa1qo66lvn6pvo8le3c63kap7291.apps.googleusercontent.com',
    iosClientId: '504400761702-bd68e16snrrbduu1duqev2ir08bhmb1g.apps.googleusercontent.com',
    iosBundleId: 'com.smartlink.smartlinkAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmoeLJQwHMUJgtd-UI9Q9t8vsxebS6fGw',
    appId: '1:504400761702:web:6228575fea1b839ba92ea7',
    messagingSenderId: '504400761702',
    projectId: 'smartlink-pro',
    authDomain: 'smartlink-pro.firebaseapp.com',
    databaseURL: 'https://smartlink-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartlink-pro.appspot.com',
    measurementId: 'G-0WP9KXYS9F',
  );
}
